.ifndef INIT_SNES_INC
INIT_SNES_INC
; -----------------------------------------------------------------------------
;   File: InitSNES.inc
;   Description: Reset the SNES to a known state
; -----------------------------------------------------------------------------

; ---- Import -----------------------------------------------------------------
.import     ClearRegisters
.import     ClearVRAM
.import     ClearCGRAM
.import     ClearOAMRAM
;-------------------------------------------------------------------------------

.endif